Feature/card swipper
LiorGnieslawMoveo/Epicure-Frontend pull request #7
Opened 2024-03-20 12:30 UTC by LiorGnieslawMoveo

2024-03-20 16:01 UTC, Karina-Moveo requested changes

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.tsx
> +                </Swiper>
The swiper here is very heavy, you can shorten it by utilizing a data file just like you did with dishes etc..

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/constants/RestaurantsData.ts
> +const RestaurantsData = {
Add your type here

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/constants/DishesData.ts
> +const DishesData = {
here also add your type

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/components/Hero/Hero.scss
>                  font-size: 23.8px;
why is the font size not a round number

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/components/Header/Header.scss
> +                justify-content: unset;
why are you using unset here?

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.scss
> +        margin-top: 18.2px;
Why is your margin not a round number?

2024-03-20 16:01 UTC, Karina-Moveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.scss
> +    margin-left: 19px;
usually it's not very good if you have margin only on one side like this
it may cause issues on the other side in responsive modes

2024-03-20 16:47 UTC, LiorGnieslawMoveo commented on epicure-frontend/src/components/Header/Header.scss
> +                justify-content: unset;
because of default settings

2024-03-20 16:47 UTC, LiorGnieslawMoveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.scss
> +        margin-top: 18.2px;
its according to the figma, i can round it

2024-03-21 06:54 UTC, Karina-Moveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.scss
> +        margin-top: 18.2px;
Round it and use round numbers for margins, sizes etc... 
Also try to use the general flex settings as much as you can

2024-03-21 06:57 UTC, Karina-Moveo requested changes

2024-03-21 06:57 UTC, Karina-Moveo commented on epicure-frontend/src/components/CardSwipper/CardSwipper.tsx
>  import { Autoplay, Navigation, Pagination, Scrollbar, A11y } from "swiper/modules";
Remove unused imports

2024-03-21 06:57 UTC, Karina-Moveo commented on epicure-frontend/src/constants/DishesData.ts
> +const DishesData: { title: string, cards: cardProps[] } = {
Do you have a specific type for Data like this? If not, add it

2024-03-21 14:13 UTC, Karina-Moveo approved these changes

2024-03-21 14:24 UTC, merged